// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiaa-nEZcjLQmljLTJyVovm-iZPG5gyrE',
    appId: '1:1065123476454:web:e679d971f11b037d2c9c27',
    messagingSenderId: '1065123476454',
    projectId: 'redem-9e143',
    authDomain: 'redem-9e143.firebaseapp.com',
    storageBucket: 'redem-9e143.appspot.com',
    measurementId: 'G-86KT1LTPRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBERA-OscGKMdJi-ExGUA9WOmO2Ecr5ojk',
    appId: '1:1065123476454:android:fd9ce6e89255ab5a2c9c27',
    messagingSenderId: '1065123476454',
    projectId: 'redem-9e143',
    storageBucket: 'redem-9e143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2i6ctwGmNwEVDM9KkcuUuonc12xJ3RQg',
    appId: '1:1065123476454:ios:fd5d9d6dd5159d862c9c27',
    messagingSenderId: '1065123476454',
    projectId: 'redem-9e143',
    storageBucket: 'redem-9e143.appspot.com',
    iosBundleId: 'app.redem.ubu.tfg.gii202324',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2i6ctwGmNwEVDM9KkcuUuonc12xJ3RQg',
    appId: '1:1065123476454:ios:9a8ef49fe7d6be602c9c27',
    messagingSenderId: '1065123476454',
    projectId: 'redem-9e143',
    storageBucket: 'redem-9e143.appspot.com',
    iosBundleId: 'app.redem.ubu.tfg.gii202324.RunnerTests',
  );
}
